/*
// <auto-generated />
using System;
using MetaHammer.Persistence.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetaHammer.Persistence.PostgreSQL.Migrations
{
    [DbContext(typeof(MetaHammerDbContext))]
    partial class MetaHammerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetaHammer.Persistence.PostgreSQL.Entities.MetaObjectDM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetaTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Relations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetaTypeId");

                    b.HasIndex("Properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "gin");

                    b.HasIndex("Relations");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Relations"), "gin");

                    b.HasIndex("TenantId");

                    b.ToTable("MetaObjects", (string)null);
                });

            modelBuilder.Entity("MetaHammer.Persistence.PostgreSQL.Entities.MetaTypeDM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MetaProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MetaRelations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("MetaTypes", (string)null);
                });

            modelBuilder.Entity("MetaHammer.Persistence.PostgreSQL.Entities.MetaObjectDM", b =>
                {
                    b.HasOne("MetaHammer.Persistence.PostgreSQL.Entities.MetaTypeDM", "MetaType")
                        .WithMany()
                        .HasForeignKey("MetaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetaType");
                });
#pragma warning restore 612, 618
        }
    }
}
*/
