<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Instances\Commands\" />
      <Folder Include="Features\Instances\Handlers\" />
      <Folder Include="Features\Instances\Queries\" />
      <Folder Include="Features\Types\Commands\" />
      <Folder Include="Features\Types\Handlers\" />
      <Folder Include="Features\Types\Queries\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MetaHammer.Domain\MetaHammer.Domain.csproj" />
      <ProjectReference Include="..\MetaHammer.Persistence.Neo4j\MetaHammer.Persistence.Neo4j.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.0.0" />
    </ItemGroup>

</Project>
